default: &default    
  adapter: postgresql    
  encoding: unicode    
  host: db    
  username: postgres    
  password: password    
  pool: 5    
    
development:    
  <<: *default    
  database: bored_development    
    
    
test:    
  <<: *default    
  database: bored_test
